package Plane;

public interface Constants {
    double FUESALAGE_LENGTH_MAX = 60.92;
    double FUESALAGE_LENGTH_MIN = 15.24;
    double WING_LOCATION_MAX = FUESALAGE_LENGTH_MAX/2 ;
    double WING_LOCATION_MIN = 0;
    double STABALIZER_LOCATION_MAX = FUESALAGE_LENGTH_MAX/2;
    double STABALIZER_LOCATION_MIN = 0;
    double VERTICAL_STABALIZER_LOCATION_MAX = FUESALAGE_LENGTH_MAX/2;
    double VERTICAL_STABALIZER_LOCATION_MIN = 0;
    double NOSE_MASS_MAX = 30;
    double NOSE_MASS_MIN = 0;

    double WING_SPAN_MAX = 33.51;
    double WING_SPAN_MIN = 1;
    double WING_TAPER_RATIO_MAX = 1;
    double WING_TAPER_RATION_MIN = 0;
    double WING_ROOT_CHORD_MAX = 7.62;
    double WING_ROOT_CHORD_MIN = 1;
    double WING_LSEA_MAX = 30;
    double WING_LSEA_MIN = 0;

    double STABALIZER_SPAN_MAX = 18.28;
    double STABALIZER_SPAN_MIN = 1;
    double STABALIZER_TAPER_RATIO_MAX = 1;
    double STABALIZER_TAPER_RATION_MIN = 0;
    double STABALIZER_ROOT_CHORD_MAX = 7.62;
    double STABALIZER_ROOT_CHORD_MIN = 1;
    double STABALIZER_LSEA_MAX = 30;
    double STABALIZER_LSEA_MIN = 0;

    double VSTABALIZER_HEIGHT_MAX = 9.14;
    double VSTABALIZER_HEIGHT_MIN = 1;
    double VSTABALIZER_TAPER_RATIO_MAX = 1;
    double VSTABALIZER_TAPER_RATION_MIN = 0;
    double VSTABALIZER_ROOT_CHORD_MAX = 7.62;
    double VSTABALIZER_ROOT_CHORD_MIN = 1;
    double VSTABALIZER_LSEA_MAX = 30;
    double VSTABALIZER_LSEA_MIN = 0;

}

